### ISSUE TITLE
Filtered Particles: Mark as Duplicate

### ISSUE THREAD

**Issue by skuschel** [openPMD/openPMD-standard#42]
Some PIC Codes (such as EPOCH) have the ability to dump particle subsets based on a variable set of requirements. For Example: in LWFA dump only the electrons that have gamma >2. Is this planned?
### Alternative Idea

@skuschel [commented](https://github.com/ComputationalRadiationPhysics/openPMD/issues/83#issue-102083290)

Instead of marking duplicates we could mark entries as 'original' data, meaning: not downsampled, not only a part of the simulation grid: the grid is the actual full simulation grid and the data is the actual quantitiy, that was used for calculations. for a particle species: the particle species is complete, this is not a subset.

**Comment by ax3l** [comment]
PIConGPU just recently learned the same feature and we are currently assigning user-defined filters a (user-chosen) name and store particles as `speciesName_filter` in the `particlesPath`.

Nevertheless, we clearly separate the concept of checkpoints and regular dumps so that we can not mismatch them in the same file (also, the simulation is aware of the pre-defined "all" filter).

**Comment by ax3l** [comment]
Coming back to this proposal for 1.1/2.0:

> Instead of marking duplicates we could mark entries as 'original' data, meaning: not downsampled, not only a part of the simulation grid: the grid is the actual full simulation grid and the data is the actual quantitiy, that was used for calculations. for a particle species: the particle species is complete, this is not a subset.

Instead of the name "duplicate" which only applies for filtered subset but not for diagnostic "probe" and "test" particles: we could also just add an attribute for particle records such as `diagnostics` (default if unset: not a "duplicate/diagnostics" particle.

**Comment by ax3l** [comment]
We discussed this issue today and it is on the border of "complicate the (base) standard a little" vs. "just write diagnostics into a new file".

If one implements it in the base standard, I would suggest that "general" base readers just read such records as usual but expose somewhere in there meta-data attributes the flag, so users can react on it e.g. during loops over all records of an iteration. But this might already be too specific for the base standard, as @RemiLehe noted.

What we can definitely do is add an optional record attribute to the `ED-PIC` extension so calculations for e.g. a local charge density ignore certain records. If this turns out to be very useful, we can always move it to be base standard later on.

**Comment by RemiLehe** [comment]
Well, in fact, even with the above proposed attribute, the main use case (looping over particles and calculating charge density) is not guaranteed to work. 

This is because openPMD files have no way of guaranteeing that *all* species have been written in the file (and, even for one given species, that all macroparticles have been written in the file). For instance, in the LWFA simulations that I routinely perform (and which feature ions and electrons), it is very common that I do not write the ions at all in the openPMD file, and that I only write the electrons above a certain energy. (In the context of this issue, these electrons would be labeled as `duplicate`, but the thing is that the full set of electrons from which they are selected is never written to the file).
So with this type of file, even with the `duplicate` (or `diagnostics`) attribute, automatically looping over the available species/macroparticles would not produce the right charge density.

So for this use case, in the context of openPMD, I would say that the user is responsible for knowing what he wrote in the file. As @ax3l  suggested, one possibility for partially automatizing the process would be to save diagnostics particles in a seperate file. 

Therefore, my inclination would be to close this issue. Would that be fine with you @skuschel ?

**Comment by skuschel** [comment]
In comparison to #200 the purpose of this issue was solely, to create and automated way to choose particle groups in order to get a full set of particles and none twice. I realize this was not as clearly written: Assuming you have particles, which belong into multiple particle groups. They would also be dumped multiple times and using all dumped particle positions to calculate e.g. the plasma density would lead to wrong results.
I actually meant to mark an entire particle group as "duplicate" or "filtered", not each individual particle!

**Comment by ax3l** [comment]
Yep, just cross-linked it because it's similar. In both cases a particle record would still be best (can be scalar and constant) for maximum flexibiliity.

The issue with this request here was , that we do not guarantee to have a *complete* dump in openPMD data set (and we soldom do dump complete particles in PIConGPU for instance). Therefore calculating a "total charge", etc. is hard to automate with guarantees.

Just annotating in general that a particle species (or some of its particles) are the result of a filter, duplication, absorption in a boundary, etc. is quite similar.

**Comment by skuschel** [comment]
That is correct, you do not have a guarantee, which is probably the best reason against this. I like the way you described it for PIConGPU: just adding `_filter` to the group name. This is clearly human readable, and at the end of the day, the user must decide what species to include. That might totally resolve the problem by itself.
